// layout.tsx (Server Component)
// import { ClerkProvider } from "@clerk/nextjs";
import "../styles/globals.css";
import ClientProviderWrapper from "./ClientProviderWrapper";

export const metadata = {
  title: " demo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviderWrapper>{children}</ClientProviderWrapper>
      </body>
    </html>
  );
}
